site_name: pytest-sample
site_description: TA new test for pytest
repo_url: https://github.com/markwayne24/pytest
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/markwayne24">markwayne24</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
